name: Database Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-db:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SQL script
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          sqlcmd -S %SQL_SERVER% -U %SQL_USERNAME% -P %SQL_PASSWORD% -i Timesheet\SqlScripts\CreateDatabaseProject.sql -o output.txt
          type output.txt
