
name: Deploy TimesheetDB2 Schema

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-database:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SQL Script
        run: |
          sqlcmd -S ${{ secrets.SQL_SERVER_HOST }} -U ${{ secrets.SQL_SERVER_USER }} -P ${{ secrets.SQL_SERVER_PASSWORD }} -i CreateDatabaseProject.sql
        env:
          SQLCMDERRORLEVEL: 0
