name: Run All SQL Server Agent Jobs

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  run-sql-jobs:
    runs-on: self-hosted  # Replace with 'windows-latest' if you're testing on a GitHub-hosted Windows runner

    steps:
    - name: Start Job: Employee
      run: |
        sqlcmd -S LAPTOP-OKDI7SQH -Q "EXEC msdb.dbo.sp_start_job @job_name='Employee'"

    - name: Wait for Job: Employee
      run: |
        powershell -Command "
          do {
            Start-Sleep -Seconds 10;
            $status = sqlcmd -S LAPTOP-OKDI7SQH -Q \"SELECT current_execution_status FROM msdb.dbo.sysjobs_view j JOIN msdb.dbo.sysjobactivity a ON j.job_id = a.job_id WHERE j.name = 'Employee' AND stop_execution_date IS NULL\" -h -1
          } while ($status -eq 1);
        "

    - name: Start Job: Client
      run: |
        sqlcmd -S LAPTOP-OKDI7SQH -Q "EXEC msdb.dbo.sp_start_job @job_name='Client'"

    - name: Wait for Job: Client
      run: |
        powershell -Command "
          do {
            Start-Sleep -Seconds 10;
            $status = sqlcmd -S LAPTOP-OKDI7SQH -Q \"SELECT current_execution_status FROM msdb.dbo.sysjobs_view j JOIN msdb.dbo.sysjobactivity a ON j.job_id = a.job_id WHERE j.name = 'Client' AND stop_execution_date IS NULL\" -h -1
          } while ($status -eq 1);
        "

    - name: Start Job: Leave
      run: |
        sqlcmd -S LAPTOP-OKDI7SQH -Q "EXEC msdb.dbo.sp_start_job @job_name='Leave'"

    - name: Wait for Job: Leave
      run: |
        powershell -Command "
          do {
            Start-Sleep -Seconds 10;
            $status = sqlcmd -S LAPTOP-OKDI7SQH -Q \"SELECT current_execution_status FROM msdb.dbo.sysjobs_view j JOIN msdb.dbo.sysjobactivity a ON j.job_id = a.job_id WHERE j.name = 'Leave' AND stop_execution_date IS NULL\" -h -1
          } while ($status -eq 1);
        "

    - name: Start Job: Timesheet
      run: |
        sqlcmd -S LAPTOP-OKDI7SQH -Q "EXEC msdb.dbo.sp_start_job @job_name='Timesheet'"

    - name: Wait for Job: Timesheet
      run: |
        powershell -Command "
          do {
            Start-Sleep -Seconds 10;
            $status = sqlcmd -S LAPTOP-OKDI7SQH -Q \"SELECT current_execution_status FROM msdb.dbo.sysjobs_view j JOIN msdb.dbo.sysjobactivity a ON j.job_id = a.job_id WHERE j.name = 'Timesheet' AND stop_execution_date IS NULL\" -h -1
          } while ($status -eq 1);
        "
